---
- name: workstationの準備
  hosts: all
  gather_facts: False
  become: yes
  become_user: root

  tasks:

  - name: gitのインストール
    yum:
      name: git
      state: latest

  - name: expectのインストール
    yum:
      name: expect
      state: latest

  - name: playbookをダウンロード(from github)
    git:
      repo: 'https://github.com/kostanaka/opentlc.git'
      dest: /root/opentlc
      force: yes

  - name: Towerへのsshキー設定
    command: /root/opentlc/inject_key.sh
