---
- name: Ansible Towerのアップデート
  hosts: tower
  gather_facts: False
  become: yes
  become_user: root

  tasks:

  - name: Towerの最新アーカイブをダウンロード
    get_url:
      dest: /root/
      url: https://releases.ansible.com/ansible-tower/setup-bundle/ansible-tower-setup-bundle-latest.el7.tar.gz

  - name: アーカイブ展開
    unarchive:
      remote_src: yes
      src: /root/ansible-tower-setup-bundle-latest.el7.tar.gz
      dest: /root/

  - name: 展開した場所へのsymlink作成
    shell: ln -sf /root/ansible-tower-setup*el7 /root/ansible-tower-setup

  - name: ansible & ansible-tower パッケージを削除
    yum:
      name: ansible, ansible-tower
      state: removed

  - name: 旧ファイルの削除
    file:
      path: /var/lib/awx
      state: absent

  - name: httpdの停止&無効化
    service:
      name: httpd
      state: stopped
      enabled: no

  - name: password設定(=>inventoryファイルを見て下さい)
    lineinfile:
      path: /root/ansible-tower-setup/inventory
      regexp: "{{ items.regexp }}"
      line: "{{ items.line }}"
    with_items:
    - regexp: '^admin_password='
      line: admin_password='{{ tower_passwords }}'
    - regexp: '^pg_password='
      line: pg_password='{{ tower_passwords }}'
    - regexp: '^rabbitmq_password='
      line: rabbitmq_password='{{ tower_passwords }}'

  - name: setupスクリプト実行
    command: /root/ansible-tower-setup/setup.sh
    args:
      chdir: /root/ansible-tower-setup
    register: result

  - name: setup.sh結果
    debug:
      msg: "{{ result }}"
   
    
