---
- name: update CloudForms (4.1 to 4.2) No.2
  hosts: cloudforms
  gather_facts: False
  become: yes
  become_user: root

  tasks:

  - name: vmdbのmigration(その1)
    shell: bash -lc "/var/www/miq/vmdb/bin/rake db:migrate"
    args:
      chdir: /var/www/miq/vmdb
    register: migration1_result

  - name: (実行結果)
    debug:
      msg: "{{ migration1_result }}"

  - name: vmdbのmigration(その2)
    shell: bash -lc "/var/www/miq/vmdb/bin/rake evm:automate:reset"
    args:
      chdir: /var/www/miq/vmdb
    register: migration2_result

  - name: (実行結果)
    debug:
      msg: "{{ migration2_result }}"

  - name: postgresql upgradeスクリプト実行
    command: /usr/bin/bash -lc "echo Y | /usr/bin/miq_postgres_upgrade.sh"
    args:
      chdir: /root
    register: upgrade_result
          
#  - name: (実行結果)
#    debug:
#      msg: "{{ upgrade_result }}"


  - name: postgresql.confの編集(1) checkpoint_segments=を削除
    lineinfile:
      path: /var/opt/rh/rh-postgresql95/lib/pgsql/data/postgresql.conf
      regexp: '^.*checkpoint_segments.*$'
      state: absent

  - name: postgresql.confの編集(2) パラメータを幾つか追加/変更
    lineinfile:
      path: /var/opt/rh/rh-postgresql95/lib/pgsql/data/postgresql.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
    - regexp: '^.*max_wal_size =.*$'
      line: '#max_wal_size = 1GB'
    - regexp: '^.*min_wal_size =.*$'
      line: '#min_wal_size = 80MB'
    - regexp: '^.*shared_preload_libraries =.*$'
      line: shared_preload_libraries = 'pglogical,repmgr_funcs'
    - regexp: '^.*wal_log_hints =.*$'
      line: 'wal_log_hints = on'

  - name: postgresqlサービスをenable & start
    service:
      name: rh-postgresql95-postgresql
      state: started
      enabled: yes

  - name: evmserverdを開始(数分お待ちください)
    service:
      name: evmserverd
      state: started
