---
- name: update CloudForms (4.1 to 4.2) No.2
  hosts: cloudforms
  gather_facts: False
  become: yes
  become_user: root

  tasks:

  - name: vmdbのmigration(その1)
    shell: bash -lc "/var/www/miq/vmdb/bin/rake db:migrate"
    args:
      chdir: /var/www/miq/vmdb
    register: migration1_result

  - name: (実行結果)
    debug:
      msg: "{{ migration1_result }}"

  - name: vmdbのmigration(その2)
    shell: bash -lc "/var/www/miq/vmdb/bin/rake evm:automate:reset"
    args:
      chdir: /var/www/miq/vmdb
    register: migration2_result

  - name: (実行結果)
    debug:
      msg: "{{ migration2_result }}"

  - name: postgresql upgradeスクリプト実行
    command: /usr/bin/bash -lc "/usr/bin/miq_postgres_upgrade.sh < (sleep 5; echo Y)"
    args:
      chdir: /root
    register: upgrade_result
          
  - name: (実行結果)
    debug:
      msg: "{{ upgrade_result }}"



