---
- name: update CloudForms (4.1 to 4.2) No.2
  hosts: cloudforms
  gather_facts: False
  become: yes
  become_user: root

  tasks:

  - name: vmdbのmigration(その1)
    shell: bash -l /var/www/miq/vmdb/bin/rake db:migrate
    args:
      chdir: /var/www/miq/vmdb
    register: migration1

  - debug:
      msg: "{{ migration1 }}"

  - name: vmdbのmigration(その2)
    shell: bash -l /var/www/miq/vmdb/bin/rake evm:automate:reset
    args:
      chdir: /var/www/miq/vmdb
    register: migration2

  - debug:
      msg: "{{ migration2 }}"

      
#  - name: postgresql upgradeスクリプト実行
#    command: /root/opentlc/pg_upgrade.sh

#  - name: postgresql.confの設定変更
    




  - name: パッケージのアップデート(all)
    yum:
      name: '*'
      state: latest
